[package]
name = "drm"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys.workspace = true
log.workspace = true
thiserror = "2.0.17"
sha2 = "0.11.0-rc.2"
rand = "0.10.0-rc.0"
env_logger = "0.11.8"
winapi = { path = "../../utils/winapi" }
